### ISSUE TITLE
add hover support

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/stain#41]
- perf doesn't matter at this point
- it's not 100% clear how API would look like (react doesn't have any `:hover` rules)

**Comment by twop** [comment]
react-native-windows supports additional events on `View`
https://github.com/Microsoft/react-native-windows/blob/26558b649cd77d29be3013593bb6cd41f9ed8dec/ReactWindows/ReactNative.Shared/UIManager/ViewExtensions.cs

```csharp
 [Flags]
        public enum MouseHandlerMask
        {
            MouseMove =        0x01,
            MouseMoveCapture = 0x02,
            MouseOver =        0x04,
            MouseOverCapture = 0x08,
            MouseOut =         0x10,
            MouseOutCapture =  0x20,
            MouseEnter =       0x40,
            MouseLeave =       0x80
}
```

I think we should make something like 
`<Touchable onMouseEnter={()=>{}} onMouseLeave={()=>{}} /> `

Also interesting source for inspiration: 
https://gist.github.com/necolas/b2d35105365c31321e7e3a0b815328b4
