### ISSUE TITLE
Add ability to 'dump' full layout as a json object

### ISSUE THREAD

**Issue by twop** [cztomsik/stain#63]
1) Really useful for debugging purposes.
2) Can be used for snapshot testing. 

From our discussion with @cztomsik 
We probably want to move text measuring to rust. In order to do that safely we need some sort of unittesting. So we can be confident switching + it would probably give a better migration scoping as well.

Example (don't attach to the shape/syntax ):
```ts
const layout = {
  view: {
    color: 'red',
    border: [1, 2, 2, 1 /* + other props*/],
    layout: { x: 50, y: 10, w: 100, h: 100 },
    children: [
      {
        text: {
          parts: [
            ['fist part', { x: 50, y: 20, w: 100, h: 10 }],
            ['second part', { x: 50, y: 40, w: 100, h: 10 }]
          ]
        }
      }
    ]
  }
}
``` 
Also we can probably just use jest snapshots to get auto diffing

**Comment by twop** [comment]
One of the interesting aspect of this is that we can potentially re-hydrate UI from the snapshot. So potentially that unlocks a possibility to startup really quickly. 

Analogy from the web world: "Serverside rendering". So this snapshot can be conceptually close to just sending html to render a page

**Comment by cztomsik** [comment]
I think easiest way is to implement Debug trait for Surface and OpResource and then all we need is to call `debug!("root {:?}", rootSurface)`

**Comment by cztomsik** [comment]
related to #77

**Comment by cztomsik** [comment]
later :)
