### ISSUE TITLE
add example browser

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/stain#7]
It might be handy (and a good example too) to have a tool where people could quickly click through all examples and show:
- a list of all examples (on the left), highlighting the one which is currently selected
- a command to run this example
- a button to actually run it
- scrollable source code (without highlighting)

This way we could also have just one npm script to run examples (no more `npm run example-*`). It will also be a little easier to run all of these examples for verification before doing a release.

Optional: Make it editable so people can play with these examples.

**Comment by twop** [comment]
I think if we want to do it with multiple windows (each example is opened in a separate window) we might want to tie that to multi window prototype. Otherwise it is easy to to within the same window.
@cztomsik  thoughts?

**Comment by cztomsik** [comment]
I think we can just start a child process (and show the command for each selected example too)

**Comment by cztomsik** [comment]
done
