### ISSUE TITLE
Mithril support

### ISSUE THREAD

**Issue by NetOperatorWibby** [cztomsik/stain#71]
[Mithril](https://mithril.js.org) seems to be better suited for SPAs but it'd be nice if I could somehow use it with `node-webrender`.

**Comment by cztomsik** [comment]
Closing for now, I'm sorry but we have enough work even without this.

If there's anybody interested in developing it, doing the PR & maintaining it in the long term, I'd be happy to merge it.

**Comment by cztomsik** [comment]
related to the latest updates (minimal DOM), this might actually happen (in some limited way) soon

**Comment by NetOperatorWibby** [comment]
NICE
