### ISSUE TITLE
add image support

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/stain#8]
It's more or less about uploading image with `txn.add_image()` and then `builder.push_image()` but we also need to decode those images (there are some rust crates but maybe it would be better to use imagemagick or some other system library, I'd love to avoid increasing binary size)

related to #39 

- [x] render image
- [x] load image from file

**Comment by twop** [comment]
Going to work on this one.

**Comment by twop** [comment]
Useful reference
https://github.com/maps4print/azul/blob/586608c202e4bc3deb55e24d5887dd9abaa9d05c/azul/src/images.rs

**Comment by cztomsik** [comment]
done (memleaky), we are using piston-image (like servo)

![image](https://user-images.githubusercontent.com/3526922/53995707-2cf7fd80-4136-11e9-9dfd-fbf6f345634e.png)
